name: CI/CD pipeline
on:
  push:
    branches:
      - 'main'
jobs:
  python_build:
    needs: postrges_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build image
        run: docker build . --file dockerfile --tag web
        
        
  postrges_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql_version: 'alpine3.17'
        env:
          POSTGRES_PASSWORD=${{secrets.postgres_password}}
          POSTGRES_USER=${{secrets.postgres_user}}
          POSTGRES_DB=${{secrets.postgres_db}}
      - name: build image
        run: docker build . --file db/dockerfile --tag postgres_db
  lint_built:
    name: Lint Code Base
    needs: python_build  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
